### PR TITLE
Port to python3

### PR DESCRIPTION
**Pull request by Wenzel**
This an attempt to bring Python3 compatibility for `pyaff4`.

I ran `futurize` over the `pyaff4` library to convert it.

I also updated two dependencies.
The compatibile version of `expiringdict` is `1.1.4`, but not yet available in `Pypi`.
see : https://github.com/mailgun/expiringdict/issues/26

I need this as an ongoing effort to get `Rekall` with Python3 compatibility also.

This is the first time i'm porting a python2 project to python3, so if you have any feedback or advice, feel free to comment.

Thanks.

### CODE REVIEW

**Comment by Wenzel** [comment]
I signed it!

**Comment by Wenzel** [comment]
I tried to run my frshly, automatically ported python 3 Rekall, and it crashed in `pyaff4`:

~~~Python
Traceback (most recent call last):
  File "/home/tarrma/Bureau/rekall_python3/venv/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekall')()
  File "/home/tarrma/Bureau/rekall_python3/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/tarrma/Bureau/rekall_python3/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/tarrma/Bureau/rekall_python3/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/tarrma/Bureau/rekall_python3/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/tarrma/Bureau/rekall_python3/rekall/rekall-core/rekall/rekal.py", line 41, in <module>
    entry_point.load()
  File "/home/tarrma/Bureau/rekall_python3/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/tarrma/Bureau/rekall_python3/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/tarrma/Bureau/rekall_python3/rekall/rekall-core/rekall/plugins/__init__.py", line 4, in <module>
    from rekall.plugins import addrspaces
  File "/home/tarrma/Bureau/rekall_python3/rekall/rekall-core/rekall/plugins/addrspaces/__init__.py", line 8, in <module>
    from rekall.plugins.addrspaces import ewf
  File "/home/tarrma/Bureau/rekall_python3/rekall/rekall-core/rekall/plugins/addrspaces/ewf.py", line 26, in <module>
    from rekall.plugins.tools import ewf
  File "/home/tarrma/Bureau/rekall_python3/rekall/rekall-core/rekall/plugins/tools/__init__.py", line 28, in <module>
    from rekall.plugins.tools import aff4acquire
  File "/home/tarrma/Bureau/rekall_python3/rekall/rekall-core/rekall/plugins/tools/aff4acquire.py", line 49, in <module>
    from pyaff4 import zip
  File "/home/tarrma/Bureau/rekall_python3/venv/lib/python3.5/site-packages/pyaff4-0.24.post3-py3.5.egg/pyaff4/zip.py", line 104, in <module>
    """)):
  File "/home/tarrma/Bureau/rekall_python3/venv/lib/python3.5/site-packages/pyaff4-0.24.post3-py3.5.egg/pyaff4/struct_parser.py", line 67, in CreateStruct
    defaults.append(int(components[3], 0))
ValueError: invalid literal for int() with base 0: '0644'
~~~
If i print the content of `components` just before the error:

~~~Python
['uint32_t', 'external_file_attr', '=', '0644', '<<', '16L']
~~~

I'm not really sure of the fix here.
If someone knows this code, i would appreciate his comments.

**Comment by Wenzel** [comment]
Ok, i found the issue.
PEP 3127 : https://www.python.org/dev/peps/pep-3127/
> octal literals must now be specified with a leading "0o" or "0O" instead of "0";

**Comment by Wenzel** [comment]
Hello @scudette  !

Could you take a look at this PR ?
And more generally, would like have some time to work together on porting Rekall to Python3 ?
I would like to get your feedback and advice, as I'm not a Python expert ;)

Thanks,
Mathieu

**Comment by scudette** [comment]
This looks good thanks!

Do you think we can just continue with this style changes in the Rekall codebase to get it up to scratch?

**Comment by Wenzel** [comment]
> Do you think we can just continue with this style changes in the Rekall codebase to get it up to scratch?

I'm just running `futurize`, updating the dependencies, and fixing the issues as they appear.
If you think their is a better way to proceed, i'm open to suggestions :)

But i think the first thing to do is to get every Rekall dependency Python3 compatible.

From the PR i opened here : https://github.com/google/rekall/pull/272

I'm blocked by:
- `expiringdict`
- `rekall-capstone` : https://github.com/scudette/rekall-capstone/pull/2
- `ipaddr` : https://github.com/google/ipaddr-py/issues/122

**Comment by scudette** [comment]
I think expringdict is abandoned and they said we should maybe use ttldict which seems like just a fork. I think ipaddr is also probably abandoned, maybe we can just fork it too.  I will look into this tomorrow.

**Comment by Wenzel** [comment]
@scudette someone just uploaded `expiringdict 1.1.4`, and it works.
Just need to fork `ipaddr`

**Comment by grrrrrrrrr** [comment]
I'd highly recommend against forking dependencies, especially if you think that they are abandoned.

The maintainer of ipaddr works at Google, maybe @scudette can ping him? If ipaddr is really abandoned, finding a replacement seems like the better way to approach this.

**Comment by scudette** [comment]
The issue is not that we can't find someone at Google to commit the fix to the repository - it is that no one seems to have access to pypi to upload the package. According to https://github.com/google/ipaddr-py/issues/122 shields@ is the only one with pypi access and he seems to have left.

I guess we could open a ticket with pypi to get the project restored but this is up to the ipaddr team to sort out with shields@. It just seems easier to push the project as another pypi name to satisfy Rekall's dependency since Rekall's goal is to be completely installable via pypi and pip.

Rekall already has a number of pypi packages which fix various other projects to make them suitable for pypi distribution so it is not a big problem. Normally we have an automated way to keep these in sync (because usually the only changes are packaging related changes for pypi).  It usually does not matter too much because we normally pin dependency versions so the exact package we need will be served by pypi.

**Comment by grrrrrrrrr** [comment]
I pinged mshields, he'd like to delegate access for ipaddr. @mbward has offered to take it already in the linked https://github.com/google/ipaddr-py/issues/122 and mshields would be ok with that solution so we should probably aim for that. I'll try to arrange this.

**Comment by schatzforensic** [comment]
Did anyone run the unit tests on this PR with Python 2.7 before submitting the patch, or applying the PR? The tests crash and burn. @scudette, will you please revert this PR?

**Comment by grrrrrrrrr** [comment]
mshields has added @mbward to https://pypi.python.org/pypi/ipaddr so he can now do the pypi release.

For the breakage, I'd highly recommend setting up Travis tests so this gets noted before the PR goes in.

**Comment by scudette** [comment]
Yes I noticed the breakage when I was playing with it. The python3 conversion tool accidentally replaced "next" with "__next__" - I guess its a dumb string replacement. @Wenzel could you please replace those back? When I was playing with it I just fixed it on the spot and kept going.

We should set up some kind of travis integration.

**Comment by Wenzel** [comment]
Hi,
The PR is opened: https://github.com/google/aff4/pull/22
I guess this is what you meant.

How should i run the tests for `pyaff4` ?

**Comment by scudette** [comment]
you just run setup.py test

**Pull request merged**
